  name: Build
  on: push
  jobs:      
    build-ci:
      runs-on: macos-latest
      name: Mac Build
      steps:
        - name: Checkout
          uses: actions/checkout@v2
              
        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 7.x
        
        - name: Install MAUI Workload
          run: |
            dotnet workload install maui-maccatalyst

        - name: Restore Dependencies
          run: dotnet restore src/Spacetime/Spacetime.csproj

        - name: Build Spacetime
          run: dotnet build src/Spacetime/Spacetime.csproj -f:net7.0-maccatalyst -c Release
          
