  name: Windows
  
  on: 
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:
  jobs:      
    build-windows:
      runs-on: windows-2022
      name: Windows Build
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Install MAUI Workload
        run: |
          dotnet workload install maui
      - name: Restore Dependencies
        run: dotnet restore src/Spacetime/Spacetime.csproj

      - name: Build Spacetime
        run: dotnet build src/Spacetime/Spacetime.csproj -f:net7.0-windows -c Release

      # - name: Upload Windows Artifact
      #   uses: actions/upload-artifact@v2.3.1
      #   with:
      #     name: windows-ci-build
      #     path: src/MauiBeach/bin/Release/net6.0-windows*/**/MauiBeach*.msix
