  name: Windows
  
  on: 
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:
  jobs:      
    build-windows:
      runs-on: windows-2022
      name: Windows Build
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup .NET 6
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.0.x
            include-prerelease: true
        
        - name: Install MAUI Workloads
          run: |
            dotnet workload install maui --ignore-failed-sources --include-previews

        - name: Restore Dependencies
          run: dotnet restore src/Spacetime/Spacetime.csproj

        - name: Build Spacetime
          run: dotnet build src/Spacetime/Spacetime.csproj -c Release

      # - name: Upload Windows Artifact
      #   uses: actions/upload-artifact@v2.3.1
      #   with:
      #     name: windows-ci-build
      #     path: src/MauiBeach/bin/Release/net6.0-windows*/**/MauiBeach*.msix
